default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: amazon_development

test:
  <<: *default
  database: amazon_test

production:
  <<: *default
  database: amazon_production
